include ../Makefile.inc

GEN_EXE = real_timer alarm t_nanosleep t_nanosleep_mod null_evp ptmr_sigev_signal ptmr_sigev_signal_mod

LINUX_EXE =

EXE = ${GEN_EXE} ${LINUX_EXE}

all : ${EXE}

allgen : ${GEN_EXE}

LDLIBS = ${IMPL_LDLIBS} ${LINUX_LIBACL}

clean :
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

${EXE} : ${TLPI_LIB}		# True as a rough approximation
